# Warhammer 40k Multi-Agent Simulator Configuration
# =================================================
# 
# This configuration file centralizes all settings for the simulation system.
# Modify these values to customize simulation behavior without changing code.

# Simulation Parameters
# ---------------------
simulation:
  # Number of turns to execute in a simulation run
  turns: 3
  
  # Maximum number of agents allowed in a single simulation
  max_agents: 10
  
  # Timeout for API calls (in seconds)
  api_timeout: 30
  
  # Logging level for simulation output
  logging_level: INFO

# File Paths
# ----------
paths:
  # Directory containing character sheet files
  character_sheets_path: .
  
  # Path to the campaign log file
  log_file_path: campaign_log.md
  
  # Directory for saving narrative outputs
  output_directory: demo_narratives
  
  # Directory for saving test outputs
  test_narratives_directory: test_narratives
  
  # Directory for simulation logs
  simulation_logs_directory: .

# Character Configuration
# ----------------------
characters:
  # Default character directories to load
  default_sheets:
    - characters/krieg
    - characters/ork
  
  # Maximum number of character actions per turn
  max_actions_per_turn: 5

# DirectorAgent Configuration
# ---------------------------
director:
  # Campaign log file name
  campaign_log_filename: campaign_log.md
  
  # World state database file (optional)
  world_state_file: null
  
  # Maximum turn history to keep in memory
  max_turn_history: 100
  
  # Error threshold before degraded operation
  error_threshold: 10

# ChroniclerAgent Configuration
# -----------------------------
chronicler:
  # Maximum events to process in a single batch
  max_events_per_batch: 50
  
  # Default narrative style
  narrative_style: grimdark_dramatic
  
  # Output directory for narrative files
  output_directory: demo_narratives

# LLM Integration (Future Use)
# ----------------------------
llm:
  # API endpoint for LLM service
  api_endpoint: null
  
  # API key for authentication
  api_key: null
  
  # Model to use for text generation
  model: null
  
  # Maximum tokens per request
  max_tokens: 1000
  
  # Temperature for response generation
  temperature: 0.7

# Testing Configuration
# ---------------------
testing:
  # Enable test mode
  test_mode: false
  
  # Directory for test output files
  test_output_directory: test_outputs
  
  # Timeout for test operations (in seconds)
  test_timeout: 30

# Performance Settings
# --------------------
performance:
  # Enable performance monitoring
  enable_monitoring: false
  
  # Maximum memory usage (MB)
  max_memory_mb: 512
  
  # Enable caching
  enable_caching: true

# Feature Flags
# -------------
features:
  # Enable AI-enhanced narrative generation
  ai_enhanced_narratives: false
  
  # Enable advanced world state management
  advanced_world_state: false
  
  # Enable multiplayer support
  multiplayer_support: false
  
  # Enable real-time updates
  realtime_updates: false

# Security Configuration
# ----------------------
security:
  # Enable security headers (production recommended)
  enable_security_headers: true
  
  # Force HTTPS in production
  force_https: false
  
  # Enable input validation
  enable_input_validation: true
  
  # Enable rate limiting
  enable_rate_limiting: true
  
  # Maximum file upload size (MB)
  max_upload_size_mb: 10
  
  # Session timeout (minutes)
  session_timeout_minutes: 60
  
  # Enable audit logging
  enable_audit_logging: true
  
  # Database encryption (future implementation)
  enable_database_encryption: false

# Production Hardening
# --------------------
production:
  # Disable debug features in production
  disable_debug_features: true
  
  # Disable API documentation in production
  disable_api_docs: false
  
  # Enable comprehensive logging
  enable_comprehensive_logging: true
  
  # Enable performance monitoring
  enable_performance_monitoring: true
  
  # Enable health checks
  enable_health_checks: true
  
  # Enable graceful shutdown
  enable_graceful_shutdown: true

# Validation Rules
# ----------------
validation:
  # Require character sheets to exist before starting simulation
  require_character_sheets: true
  
  # Validate campaign log format
  validate_campaign_log: true
  
  # Check file permissions before starting
  check_file_permissions: true