# Novel Engine Configuration
# This file contains system-wide configuration settings

# System Configuration
system:
  name: "Novel Engine"
  version: "1.0.0"
  environment: "development"  # development, testing, production
  debug_mode: true
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL

# Legal and Compliance Settings
legal:
  # Legal safeguards activation
  enable_safeguards: true
  
  # Compliance mode: "standard" or "fan"
  # - standard: No special restrictions, full functionality
  # - fan: Enables fan fiction compliance with usage restrictions
  compliance_mode: "standard"
  
  # Registry file for fan mode compliance tracking
  registry_file: "private/registry.yaml"
  
  # Content filtering settings
  content_filtering:
    enable: true
    severity: "moderate"  # strict, moderate, permissive

# IP Filtering Configuration
ip_filtering:
  # Enable IP cleaning and content filtering
  enable: true
  
  # Automatic cleaning during content generation
  auto_clean: true
  
  # Confidence threshold for automatic actions (0.0-1.0)
  confidence_threshold: 0.8
  
  # Whitelist terms (safe to use regardless of rules)
  whitelist:
    - "Imperial"
    - "Guard"
    - "Marine"
    - "Warrior"
    - "Commander"
    - "Captain"
    - "Regiment"
    - "Company"
  
  # Replacement dictionary for common terms
  replacements:
    "Space Marine": "Imperial Marine"
    "Commissar": "Officer"
    "Lasgun": "Energy Rifle"
    "Bolter": "Combat Rifle"
    "Chainsword": "Power Blade"
    "Flamer": "Flame Unit"
    "Melta": "Thermal Weapon"
    "Plasma": "Energy Weapon"
  
  # Custom filtering rules
  custom_rules:
    # Character/Unit types
    - pattern: "\\b(Primarch|Astartes|Adeptus)\\b"
      type: "character_name"
      action: "replace"
      replacement: "Imperial Elite"
      confidence: 0.9
      case_sensitive: false
      word_boundary: true
    
    # Faction names
    - pattern: "\\b(Imperium of Man|Chaos Marines|Death Guard|Blood Angels)\\b"
      type: "faction_name" 
      action: "generic"
      confidence: 0.85
      case_sensitive: false
      word_boundary: true
    
    # Location names
    - pattern: "\\b(Terra|Holy Terra|Macragge|Cadia|Ultramar)\\b"
      type: "location_name"
      action: "replace"
      replacement: "Capital World"
      confidence: 0.8
      case_sensitive: false
      word_boundary: true
    
    # Trademarked terms (blocking level)
    - pattern: "\\b(Warhammer|Games Workshop|Black Library)\\b"
      type: "trademark"
      action: "block"
      confidence: 0.95
      case_sensitive: false
      word_boundary: true
    
    # Copyrighted phrases
    - pattern: "In the grim darkness of the far future"
      type: "copyrighted_phrase"
      action: "replace"
      replacement: "In a dark and distant future"
      confidence: 0.99
      case_sensitive: false
      word_boundary: false

# API Server Configuration
api:
  host: "localhost"
  port: 8000
  cors_enabled: true
  cors_origins: ["http://localhost:3000", "http://localhost:8080"]
  max_request_size: "10MB"
  timeout: 300  # seconds

# Database and Storage
storage:
  # Knowledge base storage
  kb_type: "file"  # file, redis, postgresql
  kb_path: "private/knowledge_base/"
  
  # Session and state storage
  session_storage: "memory"  # memory, file, redis
  session_path: "private/sessions/"
  
  # Cache configuration
  cache:
    enabled: true
    type: "memory"  # memory, redis, file
    ttl: 3600  # seconds
    max_size: "100MB"

# AI/LLM Configuration
ai:
  # Default provider settings
  provider: "openai"  # openai, anthropic, local
  
  # Model configurations
  models:
    default: "gpt-4"
    fast: "gpt-3.5-turbo"
    creative: "gpt-4"
  
  # Token budgets and limits
  token_budgets:
    per_turn: 8000
    per_session: 100000
    emergency_reserve: 2000
  
  # Rate limiting
  rate_limits:
    requests_per_minute: 60
    tokens_per_minute: 40000

# Simulation Engine Settings
simulation:
  # Turn processing
  max_agents_per_turn: 20
  turn_timeout: 120  # seconds
  
  # World state management
  max_world_entities: 1000
  entity_cleanup_threshold: 0.8
  
  # Iron Laws validation
  iron_laws:
    enabled: true
    repair_attempts: 3
    strict_mode: false  # If true, no repair attempts
  
  # Fog of War settings
  fog_of_war:
    enabled: true
    default_visual_range: 10
    default_radio_range: 50
    default_intel_range: 100

# Performance and Optimization
performance:
  # Caching strategies
  semantic_cache:
    enabled: true
    similarity_threshold: 0.95
    max_entries: 1000
  
  # Parallel processing
  max_workers: 4
  async_enabled: true
  
  # Resource monitoring
  memory_limit: "2GB"
  cpu_limit: 80  # percentage

# Monitoring and Logging
monitoring:
  # Metrics collection
  metrics_enabled: true
  metrics_port: 9090
  
  # Health checks
  health_check_interval: 30  # seconds
  
  # Error reporting
  error_reporting:
    enabled: true
    level: "ERROR"
    include_traceback: true

# Development and Testing
development:
  # Hot reload for development
  hot_reload: true
  
  # Test configuration
  test_mode: false
  mock_ai_responses: false
  
  # Debug features
  debug:
    log_requests: true
    log_responses: false
    save_intermediate_states: true
    profile_performance: false

# Security Settings
security:
  # API security
  require_api_key: false
  api_key_header: "X-API-Key"
  
  # Input validation
  strict_validation: true
  sanitize_inputs: true
  
  # Rate limiting per client
  client_rate_limits:
    enabled: true
    requests_per_hour: 1000
    burst_size: 100

# Feature Flags
features:
  # Experimental features
  experimental_features: false
  
  # Module toggles
  modules:
    evaluation_pipeline: true
    metrics_collection: true
    advanced_caching: false
    multi_language_support: false

# Paths and Directories
paths:
  # Core directories
  src: "src/"
  tests: "tests/"
  docs: "docs/"
  scripts: "scripts/"
  
  # Data directories
  private: "private/"
  evaluation: "evaluation/"
  
  # Output directories
  logs: "logs/"
  exports: "exports/"
  backups: "backups/"

# External Integrations
integrations:
  # Version control
  git:
    enabled: true
    auto_commit: false
  
  # CI/CD
  ci:
    provider: "github_actions"
    enabled: false
  
  # Monitoring services
  external_monitoring:
    enabled: false
    provider: "none"  # datadog, prometheus, newrelic