# Novel Engine Evaluation Pipeline Configuration
# =============================================
#
# Configuration file for automated evaluation pipeline system.
# Structure matches PipelineConfig dataclass in run_evaluation_pipeline.py

# Directory paths
seeds_directory: "evaluation/seeds"
results_directory: "evaluation/results" 
archive_directory: "evaluation/archive"

# Pipeline scheduling
run_mode: "manual"  # manual, daily, weekly, ci
max_execution_time: 3600  # seconds

# Performance monitoring
enable_performance_tracking: true
performance_baseline_file: "evaluation/baseline_performance.json"
regression_threshold: 0.1  # 10% performance degradation threshold

# Quality gates
minimum_pass_rate: 0.85  # 85% of seeds must pass
maximum_violation_rate: 0.05  # 5% violation rate maximum
critical_violation_threshold: 10  # Alert if violations exceed this

# Reporting
generate_html_report: true
generate_trend_analysis: true
save_detailed_logs: true

# Alerting (optional)
email_alerts: false
email_recipients: []
smtp_server: ""
smtp_port: 587