/**
 * Stable application error-code catalog shared by domain, application, and
 * interface layers. Every emitted SCREAMING_SNAKE error code derives here.
 */
export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CSRF_TOKEN_MISSING: "CSRF_TOKEN_MISSING",
  CSRF_TOKEN_INVALID: "CSRF_TOKEN_INVALID",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  NOT_FOUND: "NOT_FOUND",
  INVALID_OPERATION: "INVALID_OPERATION",
  EXPORT_CAPACITY_EXCEEDED: "EXPORT_CAPACITY_EXCEEDED",
  GENERATION_CAPACITY_EXCEEDED: "GENERATION_CAPACITY_EXCEEDED",
  IMPORT_CAPACITY_EXCEEDED: "IMPORT_CAPACITY_EXCEEDED",
  STRUCTURE_CAPACITY_EXCEEDED: "STRUCTURE_CAPACITY_EXCEEDED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  REVISION_CONFLICT: "REVISION_CONFLICT",
  VOLUME_CONFLICT: "VOLUME_CONFLICT",
  SNAPSHOT_CONFLICT: "SNAPSHOT_CONFLICT",
  DOCUMENT_CONFLICT: "DOCUMENT_CONFLICT",
  OPERATION_IN_FLIGHT: "OPERATION_IN_FLIGHT",
  OPERATION_CAPACITY_EXCEEDED: "OPERATION_CAPACITY_EXCEEDED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
