"""Schema package for the Novel Engine API.

This package provides all Pydantic schemas used by the API layer.
The schemas are organized into modular files for maintainability:

- character_schemas.py: Character-related schemas (psychology, memory, goals, generation)
- narrative_schemas.py: Narrative structure schemas (stories, chapters, scenes, beats, plotlines)
- orchestration_schemas.py: Orchestration status/control schemas
- system_schemas.py: Health, auth, campaign, workspace, event, analytics schemas
- social_schemas.py: Relationship, item, faction, social network schemas
- lore_schemas.py: Lore entry, world rule, smart tags schemas
- knowledge_schemas.py: RAG, brain settings, routing, knowledge base schemas
- experiment_schemas.py: Prompt management, A/B testing, analytics schemas
- world_schemas.py: Calendar, diplomacy, simulation, snapshot, rumor schemas
- remaining_schemas.py: Catch-all for remaining schemas (to be organized in future)

Backward Compatibility:
    All imports continue to work as before:
        from src.api.schemas import CharacterGenerationResponse

Created as part of PREP-001 (Operation Vanguard).
Updated in PREP-002 to further modularize schemas.
"""

# Re-export all character schemas
from src.api.schemas.character_schemas import (
    CharacterDetailResponse,
    CharacterGenerationRequest,
    CharacterGenerationResponse,
    CharacterGoalCreateRequest,
    CharacterGoalSchema,
    CharacterGoalUpdateRequest,
    CharacterGoalsResponse,
    CharacterMemoriesResponse,
    CharacterMemoryCreateRequest,
    CharacterMemorySchema,
    CharacterMemoryUpdateRequest,
    CharacterProfileGenerationRequest,
    CharacterProfileGenerationResponse,
    CharacterPsychologySchema,
    CharacterSummary,
    CharactersListResponse,
    DialogueGenerationRequest,
    DialogueGenerationResponse,
)

# Re-export all narrative schemas
from src.api.schemas.narrative_schemas import (
    BeatCreateRequest,
    BeatListResponse,
    BeatResponse,
    BeatSuggestion,
    BeatSuggestionRequest,
    BeatSuggestionResponse,
    BeatUpdateRequest,
    ChapterCreateRequest,
    ChapterHealthReportResponse,
    ChapterListResponse,
    ChapterPacingResponse,
    ChapterResponse,
    ChapterUpdateRequest,
    ConflictCreateRequest,
    ConflictListResponse,
    ConflictResponse,
    ConflictUpdateRequest,
    CritiqueCategoryScoreResponse,
    CritiqueSceneRequest,
    CritiqueSceneResponse,
    ForeshadowingCreateRequest,
    ForeshadowingListResponse,
    ForeshadowingResponse,
    ForeshadowingUpdateRequest,
    HealthScoreEnum,
    HealthWarningResponse,
    LinkPayoffRequest,
    LinkSceneToPlotlineRequest,
    MoveChapterRequest,
    MoveSceneRequest,
    NarrativeData,
    NarrativeResponse,
    NarrativeStreamChunk,
    NarrativeStreamMetadata,
    NarrativeStreamRequest,
    PacingIssueResponse,
    PhaseDistributionResponse,
    PlotlineCreateRequest,
    PlotlineListResponse,
    PlotlineResponse,
    PlotlineUpdateRequest,
    ReorderBeatsRequest,
    SceneCreateRequest,
    SceneGenerationRequest,
    SceneGenerationResponse,
    SceneListResponse,
    ScenePacingMetricsResponse,
    ScenePlotlinesResponse,
    SceneResponse,
    SceneUpdateRequest,
    SetScenePlotlinesRequest,
    StoryCreateRequest,
    StoryListResponse,
    StoryResponse,
    StoryUpdateRequest,
    StructureErrorResponse,
    TensionArcShapeResponse,
    UnlinkSceneFromPlotlineRequest,
    WarningCategoryEnum,
    WordCountEstimateResponse,
    WorldContext,
    WorldContextEntity,
)

# Re-export orchestration schemas
from src.api.schemas.orchestration_schemas import (
    OrchestrationStep,
    OrchestrationStatusData,
    OrchestrationStatusResponse,
    OrchestrationStartRequest,
    OrchestrationStartResponse,
    OrchestrationStopResponse,
)

# Re-export system schemas
from src.api.schemas.system_schemas import (
    ErrorDetail,
    ValidationError,
    HealthResponse,
    HealthCheckResponse,
    SystemStatusResponse,
    PolicyInfoResponse,
    SSEEventData,
    SSEStatsResponse,
    AnalyticsMetricsData,
    AnalyticsMetricsResponse,
    SimulationRequest,
    SimulationResponse,
    FileCount,
    CampaignsListResponse,
    CampaignCreationRequest,
    CampaignCreationResponse,
    CampaignDetailResponse,
    LoginRequest,
    AuthResponse,
    LogoutRequest,
    LogoutResponse,
    TokenValidationResponse,
    RefreshTokenRequest,
    CSRFTokenResponse,
    InvalidationRequest,
    ChunkInRequest,
    GuestSessionResponse,
    WorkspaceCharacterCreateRequest,
    WorkspaceCharacterUpdateRequest,
)

# Re-export social schemas
from src.api.schemas.social_schemas import (
    RelationshipCreateRequest,
    RelationshipUpdateRequest,
    InteractionLogSchema,
    LogInteractionRequest,
    RelationshipHistoryGenerationResponse,
    RelationshipResponse,
    RelationshipListResponse,
    CharacterCentralitySchema,
    SocialAnalysisResponse,
    ItemCreateRequest,
    ItemUpdateRequest,
    ItemResponse,
    ItemListResponse,
    GiveItemRequest,
    RemoveItemResponse,
    FactionJoinRequest,
    FactionJoinResponse,
    FactionLeaveRequest,
    FactionLeaveResponse,
    FactionSetLeaderRequest,
    FactionSetLeaderResponse,
    FactionMemberSchema,
    FactionDetailResponse,
)

# Re-export lore schemas
from src.api.schemas.lore_schemas import (
    LoreEntryCreateRequest,
    LoreEntryUpdateRequest,
    LoreEntryResponse,
    SmartTagsResponse,
    ManualSmartTagsUpdateRequest,
    LoreEntryListResponse,
    LoreSearchRequest,
    WorldRuleCreateRequest,
    WorldRuleUpdateRequest,
    WorldRuleResponse,
    WorldRuleListResponse,
)

# Re-export knowledge schemas
from src.api.schemas.knowledge_schemas import (
    TaskRoutingRuleSchema,
    RoutingConstraintsSchema,
    CircuitBreakerRuleSchema,
    RoutingConfigResponse,
    RoutingConfigUpdateRequest,
    RoutingConfigResetRequest,
    RoutingStatsResponse,
    APIKeysRequest,
    APIKeysResponse,
    RAGConfigRequest,
    RAGConfigResponse,
    KnowledgeBaseStatusResponse,
    BrainSettingsResponse,
    RetrievedChunkResponse,
    RAGContextResponse,
    ConfidentialityLevel,
    KnowledgeMetadataSchema,
    IngestionJobStatus,
    StartIngestionJobRequest,
    IngestionJobResponse,
    StartIngestionJobResponse,
)

# Re-export experiment schemas
from src.api.schemas.experiment_schemas import (
    PromptVariableDefinition,
    PromptVariableValue,
    PromptSummary,
    PromptModelConfig,
    PromptDetailResponse,
    PromptListResponse,
    PromptCreateRequest,
    PromptUpdateRequest,
    PromptRenderRequest,
    PromptRenderResponse,
    PromptGenerateRequest,
    PromptGenerateResponse,
    PromptAnalyticsTimePeriod,
    PromptTimeSeriesDataPoint,
    PromptRatingDistribution,
    PromptAnalyticsResponse,
    PromptAnalyticsRequest,
    ExperimentMetricsResponse,
    ConfidenceIntervalResponse,
    ExperimentVariantResponse,
    ExperimentComparisonResponse,
    ExperimentTimelineResponse,
    ExperimentResultsResponse,
    ExperimentSummaryResponse,
    ExperimentListResponse,
    ExperimentCreateRequest,
    ExperimentUpdateRequest,
    ExperimentRecordRequest,
    ExperimentActionRequest,
)

# Re-export world schemas
from src.api.schemas.world_schemas import (
    HistoryEventResponse,
    CreateEventRequest,
    EventFilterParams,
    EventListResponse,
    CalendarResponse,
    AdvanceCalendarRequest,
    CalendarData,
    DiplomacyMatrixResponse,
    FactionDiplomacyResponse,
    SetRelationRequest,
    SimulateRequest,
    ResourceChangesResponse,
    DiplomacyChangeResponse,
    SimulationTickSummary,
    SimulationTickResponse,
    SimulationHistoryResponse,
    SimulationStatusResponse,
    CreateSnapshotRequest,
    SnapshotSummary,
    SnapshotResponse,
    SnapshotListResponse,
    RestoreSnapshotResponse,
    SortByEnum,
    RumorResponse,
    RumorListResponse,
)

# Note: remaining_schemas.py has been fully deprecated and deleted.
# All schemas now live in domain-specific modules. Add any future schemas
# to the appropriate module file based on their domain.

# Define __all__ for clean exports
__all__ = [
    # Character schemas
    "CharacterDetailResponse",
    "CharacterGenerationRequest",
    "CharacterGenerationResponse",
    "CharacterGoalCreateRequest",
    "CharacterGoalSchema",
    "CharacterGoalUpdateRequest",
    "CharacterGoalsResponse",
    "CharacterMemoriesResponse",
    "CharacterMemoryCreateRequest",
    "CharacterMemorySchema",
    "CharacterMemoryUpdateRequest",
    "CharacterProfileGenerationRequest",
    "CharacterProfileGenerationResponse",
    "CharacterPsychologySchema",
    "CharacterSummary",
    "CharactersListResponse",
    "DialogueGenerationRequest",
    "DialogueGenerationResponse",
    # Narrative schemas
    "BeatCreateRequest",
    "BeatListResponse",
    "BeatResponse",
    "BeatSuggestion",
    "BeatSuggestionRequest",
    "BeatSuggestionResponse",
    "BeatUpdateRequest",
    "ChapterCreateRequest",
    "ChapterHealthReportResponse",
    "ChapterListResponse",
    "ChapterPacingResponse",
    "ChapterResponse",
    "ChapterUpdateRequest",
    "ConflictCreateRequest",
    "ConflictListResponse",
    "ConflictResponse",
    "ConflictUpdateRequest",
    "CritiqueCategoryScoreResponse",
    "CritiqueSceneRequest",
    "CritiqueSceneResponse",
    "ForeshadowingCreateRequest",
    "ForeshadowingListResponse",
    "ForeshadowingResponse",
    "ForeshadowingUpdateRequest",
    "HealthScoreEnum",
    "HealthWarningResponse",
    "LinkPayoffRequest",
    "LinkSceneToPlotlineRequest",
    "MoveChapterRequest",
    "MoveSceneRequest",
    "NarrativeData",
    "NarrativeResponse",
    "NarrativeStreamChunk",
    "NarrativeStreamMetadata",
    "NarrativeStreamRequest",
    "PacingIssueResponse",
    "PhaseDistributionResponse",
    "PlotlineCreateRequest",
    "PlotlineListResponse",
    "PlotlineResponse",
    "PlotlineUpdateRequest",
    "ReorderBeatsRequest",
    "SceneCreateRequest",
    "SceneGenerationRequest",
    "SceneGenerationResponse",
    "SceneListResponse",
    "ScenePacingMetricsResponse",
    "ScenePlotlinesResponse",
    "SceneResponse",
    "SceneUpdateRequest",
    "SetScenePlotlinesRequest",
    "StoryCreateRequest",
    "StoryListResponse",
    "StoryResponse",
    "StoryUpdateRequest",
    "StructureErrorResponse",
    "TensionArcShapeResponse",
    "UnlinkSceneFromPlotlineRequest",
    "WarningCategoryEnum",
    "WordCountEstimateResponse",
    "WorldContext",
    "WorldContextEntity",
    # Orchestration schemas
    "OrchestrationStep",
    "OrchestrationStatusData",
    "OrchestrationStatusResponse",
    "OrchestrationStartRequest",
    "OrchestrationStartResponse",
    "OrchestrationStopResponse",
    # System schemas
    "ErrorDetail",
    "ValidationError",
    "HealthResponse",
    "HealthCheckResponse",
    "SystemStatusResponse",
    "PolicyInfoResponse",
    "SSEEventData",
    "SSEStatsResponse",
    "AnalyticsMetricsData",
    "AnalyticsMetricsResponse",
    "SimulationRequest",
    "SimulationResponse",
    "FileCount",
    "CampaignsListResponse",
    "CampaignCreationRequest",
    "CampaignCreationResponse",
    "CampaignDetailResponse",
    "LoginRequest",
    "AuthResponse",
    "LogoutRequest",
    "LogoutResponse",
    "TokenValidationResponse",
    "RefreshTokenRequest",
    "CSRFTokenResponse",
    "InvalidationRequest",
    "ChunkInRequest",
    "GuestSessionResponse",
    "WorkspaceCharacterCreateRequest",
    "WorkspaceCharacterUpdateRequest",
    # Social schemas
    "RelationshipCreateRequest",
    "RelationshipUpdateRequest",
    "InteractionLogSchema",
    "LogInteractionRequest",
    "RelationshipHistoryGenerationResponse",
    "RelationshipResponse",
    "RelationshipListResponse",
    "CharacterCentralitySchema",
    "SocialAnalysisResponse",
    "ItemCreateRequest",
    "ItemUpdateRequest",
    "ItemResponse",
    "ItemListResponse",
    "GiveItemRequest",
    "RemoveItemResponse",
    "FactionJoinRequest",
    "FactionJoinResponse",
    "FactionLeaveRequest",
    "FactionLeaveResponse",
    "FactionSetLeaderRequest",
    "FactionSetLeaderResponse",
    "FactionMemberSchema",
    "FactionDetailResponse",
    # Lore schemas
    "LoreEntryCreateRequest",
    "LoreEntryUpdateRequest",
    "LoreEntryResponse",
    "SmartTagsResponse",
    "ManualSmartTagsUpdateRequest",
    "LoreEntryListResponse",
    "LoreSearchRequest",
    "WorldRuleCreateRequest",
    "WorldRuleUpdateRequest",
    "WorldRuleResponse",
    "WorldRuleListResponse",
    # Knowledge schemas
    "TaskRoutingRuleSchema",
    "RoutingConstraintsSchema",
    "CircuitBreakerRuleSchema",
    "RoutingConfigResponse",
    "RoutingConfigUpdateRequest",
    "RoutingConfigResetRequest",
    "RoutingStatsResponse",
    "APIKeysRequest",
    "APIKeysResponse",
    "RAGConfigRequest",
    "RAGConfigResponse",
    "KnowledgeBaseStatusResponse",
    "BrainSettingsResponse",
    "RetrievedChunkResponse",
    "RAGContextResponse",
    "ConfidentialityLevel",
    "KnowledgeMetadataSchema",
    "IngestionJobStatus",
    "StartIngestionJobRequest",
    "IngestionJobResponse",
    "StartIngestionJobResponse",
    # Experiment schemas
    "PromptVariableDefinition",
    "PromptVariableValue",
    "PromptSummary",
    "PromptModelConfig",
    "PromptDetailResponse",
    "PromptListResponse",
    "PromptCreateRequest",
    "PromptUpdateRequest",
    "PromptRenderRequest",
    "PromptRenderResponse",
    "PromptGenerateRequest",
    "PromptGenerateResponse",
    "PromptAnalyticsTimePeriod",
    "PromptTimeSeriesDataPoint",
    "PromptRatingDistribution",
    "PromptAnalyticsResponse",
    "PromptAnalyticsRequest",
    "ExperimentMetricsResponse",
    "ConfidenceIntervalResponse",
    "ExperimentVariantResponse",
    "ExperimentComparisonResponse",
    "ExperimentTimelineResponse",
    "ExperimentResultsResponse",
    "ExperimentSummaryResponse",
    "ExperimentListResponse",
    "ExperimentCreateRequest",
    "ExperimentUpdateRequest",
    "ExperimentRecordRequest",
    "ExperimentActionRequest",
    # World schemas
    "HistoryEventResponse",
    "CreateEventRequest",
    "EventFilterParams",
    "EventListResponse",
    "CalendarResponse",
    "AdvanceCalendarRequest",
    "CalendarData",
    "DiplomacyMatrixResponse",
    "FactionDiplomacyResponse",
    "SetRelationRequest",
    "SimulateRequest",
    "ResourceChangesResponse",
    "DiplomacyChangeResponse",
    "SimulationTickSummary",
    "SimulationTickResponse",
    "SimulationHistoryResponse",
    "SimulationStatusResponse",
    "CreateSnapshotRequest",
    "SnapshotSummary",
    "SnapshotResponse",
    "SnapshotListResponse",
    "RestoreSnapshotResponse",
    "SortByEnum",
    "RumorResponse",
    "RumorListResponse",
]
