"""Schema package for the Novel Engine API.

This package provides all Pydantic schemas used by the API layer.
The schemas are organized into modular files for maintainability:

- character_schemas.py: Character-related schemas (psychology, memory, goals, generation)
- narrative_schemas.py: Narrative structure schemas (stories, chapters, scenes, beats, plotlines)
- remaining_schemas.py: All other schemas (will be further modularized in PREP-002)

Backward Compatibility:
    All imports continue to work as before:
        from src.api.schemas import CharacterGenerationResponse

Created as part of PREP-001 (Operation Vanguard).
"""

# Re-export all character schemas
from src.api.schemas.character_schemas import (
    CharacterDetailResponse,
    CharacterGenerationRequest,
    CharacterGenerationResponse,
    CharacterGoalCreateRequest,
    CharacterGoalSchema,
    CharacterGoalUpdateRequest,
    CharacterGoalsResponse,
    CharacterMemoriesResponse,
    CharacterMemoryCreateRequest,
    CharacterMemorySchema,
    CharacterMemoryUpdateRequest,
    CharacterProfileGenerationRequest,
    CharacterProfileGenerationResponse,
    CharacterPsychologySchema,
    CharacterSummary,
    CharactersListResponse,
    DialogueGenerationRequest,
    DialogueGenerationResponse,
)

# Re-export all narrative schemas
from src.api.schemas.narrative_schemas import (
    BeatCreateRequest,
    BeatListResponse,
    BeatResponse,
    BeatSuggestion,
    BeatSuggestionRequest,
    BeatSuggestionResponse,
    BeatUpdateRequest,
    ChapterCreateRequest,
    ChapterHealthReportResponse,
    ChapterListResponse,
    ChapterPacingResponse,
    ChapterResponse,
    ChapterUpdateRequest,
    ConflictCreateRequest,
    ConflictListResponse,
    ConflictResponse,
    ConflictUpdateRequest,
    CritiqueCategoryScoreResponse,
    CritiqueSceneRequest,
    CritiqueSceneResponse,
    ForeshadowingCreateRequest,
    ForeshadowingListResponse,
    ForeshadowingResponse,
    ForeshadowingUpdateRequest,
    HealthScoreEnum,
    HealthWarningResponse,
    LinkPayoffRequest,
    LinkSceneToPlotlineRequest,
    MoveChapterRequest,
    MoveSceneRequest,
    NarrativeData,
    NarrativeResponse,
    NarrativeStreamChunk,
    NarrativeStreamMetadata,
    NarrativeStreamRequest,
    PacingIssueResponse,
    PhaseDistributionResponse,
    PlotlineCreateRequest,
    PlotlineListResponse,
    PlotlineResponse,
    PlotlineUpdateRequest,
    ReorderBeatsRequest,
    SceneCreateRequest,
    SceneGenerationRequest,
    SceneGenerationResponse,
    SceneListResponse,
    ScenePacingMetricsResponse,
    ScenePlotlinesResponse,
    SceneResponse,
    SceneUpdateRequest,
    SetScenePlotlinesRequest,
    StoryCreateRequest,
    StoryListResponse,
    StoryResponse,
    StoryUpdateRequest,
    StructureErrorResponse,
    TensionArcShapeResponse,
    UnlinkSceneFromPlotlineRequest,
    WarningCategoryEnum,
    WordCountEstimateResponse,
    WorldContext,
    WorldContextEntity,
)

# Import remaining schemas explicitly (will be organized in PREP-002)
# Note: We use explicit imports to avoid conflicts with narrative/character schemas
from src.api.schemas.remaining_schemas import (
    # Orchestration schemas
    OrchestrationStep,
    OrchestrationStatusData,
    OrchestrationStatusResponse,
    OrchestrationStartRequest,
    OrchestrationStartResponse,
    OrchestrationStopResponse,
    # Health/Meta schemas
    ErrorDetail,
    ValidationError,
    HealthResponse,
    HealthCheckResponse,
    SystemStatusResponse,
    PolicyInfoResponse,
    # Events/Analytics schemas
    SSEEventData,
    SSEStatsResponse,
    AnalyticsMetricsData,
    AnalyticsMetricsResponse,
    # Simulation schemas
    SimulationRequest,
    SimulationResponse,
    # Campaign schemas
    FileCount,
    CampaignsListResponse,
    CampaignCreationRequest,
    CampaignCreationResponse,
    CampaignDetailResponse,
    # Auth schemas
    LoginRequest,
    AuthResponse,
    LogoutRequest,
    LogoutResponse,
    TokenValidationResponse,
    RefreshTokenRequest,
    CSRFTokenResponse,
    InvalidationRequest,
    ChunkInRequest,
    GuestSessionResponse,
    # Workspace schemas
    WorkspaceCharacterCreateRequest,
    WorkspaceCharacterUpdateRequest,
    # Relationship schemas
    RelationshipCreateRequest,
    RelationshipUpdateRequest,
    InteractionLogSchema,
    LogInteractionRequest,
    RelationshipHistoryGenerationResponse,
    RelationshipResponse,
    RelationshipListResponse,
    CharacterCentralitySchema,
    SocialAnalysisResponse,
    # Item schemas
    ItemCreateRequest,
    ItemUpdateRequest,
    ItemResponse,
    ItemListResponse,
    GiveItemRequest,
    RemoveItemResponse,
    # Lore schemas
    LoreEntryCreateRequest,
    LoreEntryUpdateRequest,
    LoreEntryResponse,
    SmartTagsResponse,
    ManualSmartTagsUpdateRequest,
    LoreEntryListResponse,
    LoreSearchRequest,
    # World Rule schemas
    WorldRuleCreateRequest,
    WorldRuleUpdateRequest,
    WorldRuleResponse,
    WorldRuleListResponse,
    # Faction schemas
    FactionJoinRequest,
    FactionJoinResponse,
    FactionLeaveRequest,
    FactionLeaveResponse,
    FactionSetLeaderRequest,
    FactionSetLeaderResponse,
    FactionMemberSchema,
    FactionDetailResponse,
    # Prompt schemas
    PromptVariableDefinition,
    PromptVariableValue,
    PromptSummary,
    PromptModelConfig,
    PromptDetailResponse,
    PromptListResponse,
    PromptCreateRequest,
    PromptUpdateRequest,
    PromptRenderRequest,
    PromptRenderResponse,
    PromptGenerateRequest,
    PromptGenerateResponse,
    PromptAnalyticsTimePeriod,
    PromptTimeSeriesDataPoint,
    PromptRatingDistribution,
    PromptAnalyticsResponse,
    PromptAnalyticsRequest,
    # Experiment schemas
    ExperimentMetricsResponse,
    ConfidenceIntervalResponse,
    ExperimentVariantResponse,
    ExperimentComparisonResponse,
    ExperimentTimelineResponse,
    ExperimentResultsResponse,
    ExperimentSummaryResponse,
    ExperimentListResponse,
    ExperimentCreateRequest,
    ExperimentUpdateRequest,
    ExperimentRecordRequest,
    ExperimentActionRequest,
    # Routing/Brain schemas
    TaskRoutingRuleSchema,
    RoutingConstraintsSchema,
    CircuitBreakerRuleSchema,
    RoutingConfigResponse,
    RoutingConfigUpdateRequest,
    RoutingConfigResetRequest,
    RoutingStatsResponse,
    APIKeysRequest,
    APIKeysResponse,
    RAGConfigRequest,
    RAGConfigResponse,
    KnowledgeBaseStatusResponse,
    BrainSettingsResponse,
    RetrievedChunkResponse,
    RAGContextResponse,
    ConfidentialityLevel,
    KnowledgeMetadataSchema,
    IngestionJobStatus,
    StartIngestionJobRequest,
    IngestionJobResponse,
    StartIngestionJobResponse,
    # Event schemas
    HistoryEventResponse,
    CreateEventRequest,
    EventFilterParams,
    EventListResponse,
    # Calendar schemas
    CalendarResponse,
    AdvanceCalendarRequest,
    CalendarData,
    # Diplomacy schemas
    DiplomacyMatrixResponse,
    FactionDiplomacyResponse,
    SetRelationRequest,
    SimulateRequest,
    ResourceChangesResponse,
    DiplomacyChangeResponse,
    SimulationTickSummary,
    SimulationTickResponse,
    SimulationHistoryResponse,
    SimulationStatusResponse,
    # Snapshot schemas
    CreateSnapshotRequest,
    SnapshotSummary,
    SnapshotResponse,
    SnapshotListResponse,
    RestoreSnapshotResponse,
    # Rumor schemas
    SortByEnum,
    RumorResponse,
    RumorListResponse,
)

# Define __all__ for clean exports
__all__ = [
    # Character schemas
    "CharacterDetailResponse",
    "CharacterGenerationRequest",
    "CharacterGenerationResponse",
    "CharacterGoalCreateRequest",
    "CharacterGoalSchema",
    "CharacterGoalUpdateRequest",
    "CharacterGoalsResponse",
    "CharacterMemoriesResponse",
    "CharacterMemoryCreateRequest",
    "CharacterMemorySchema",
    "CharacterMemoryUpdateRequest",
    "CharacterProfileGenerationRequest",
    "CharacterProfileGenerationResponse",
    "CharacterPsychologySchema",
    "CharacterSummary",
    "CharactersListResponse",
    "DialogueGenerationRequest",
    "DialogueGenerationResponse",
    # Narrative schemas
    "BeatCreateRequest",
    "BeatListResponse",
    "BeatResponse",
    "BeatSuggestion",
    "BeatSuggestionRequest",
    "BeatSuggestionResponse",
    "BeatUpdateRequest",
    "ChapterCreateRequest",
    "ChapterHealthReportResponse",
    "ChapterListResponse",
    "ChapterPacingResponse",
    "ChapterResponse",
    "ChapterUpdateRequest",
    "ConflictCreateRequest",
    "ConflictListResponse",
    "ConflictResponse",
    "ConflictUpdateRequest",
    "CritiqueCategoryScoreResponse",
    "CritiqueSceneRequest",
    "CritiqueSceneResponse",
    "ForeshadowingCreateRequest",
    "ForeshadowingListResponse",
    "ForeshadowingResponse",
    "ForeshadowingUpdateRequest",
    "HealthScoreEnum",
    "HealthWarningResponse",
    "LinkPayoffRequest",
    "LinkSceneToPlotlineRequest",
    "MoveChapterRequest",
    "MoveSceneRequest",
    "NarrativeData",
    "NarrativeResponse",
    "NarrativeStreamChunk",
    "NarrativeStreamMetadata",
    "NarrativeStreamRequest",
    "PacingIssueResponse",
    "PhaseDistributionResponse",
    "PlotlineCreateRequest",
    "PlotlineListResponse",
    "PlotlineResponse",
    "PlotlineUpdateRequest",
    "ReorderBeatsRequest",
    "SceneCreateRequest",
    "SceneGenerationRequest",
    "SceneGenerationResponse",
    "SceneListResponse",
    "ScenePacingMetricsResponse",
    "ScenePlotlinesResponse",
    "SceneResponse",
    "SceneUpdateRequest",
    "SetScenePlotlinesRequest",
    "StoryCreateRequest",
    "StoryListResponse",
    "StoryResponse",
    "StoryUpdateRequest",
    "StructureErrorResponse",
    "TensionArcShapeResponse",
    "UnlinkSceneFromPlotlineRequest",
    "WarningCategoryEnum",
    "WordCountEstimateResponse",
    "WorldContext",
    "WorldContextEntity",
    # Add remaining schema names from remaining_schemas
    # These are imported via * so we list key ones here
    "ErrorDetail",
    "ValidationError",
    "HealthResponse",
    "HealthCheckResponse",
    "SystemStatusResponse",
    "PolicyInfoResponse",
    "SSEEventData",
    "SSEStatsResponse",
    "AnalyticsMetricsData",
    "AnalyticsMetricsResponse",
    "SimulationRequest",
    "SimulationResponse",
    "OrchestrationStep",
    "OrchestrationStatusData",
    "OrchestrationStatusResponse",
    "OrchestrationStartRequest",
    "OrchestrationStartResponse",
    "OrchestrationStopResponse",
    "FileCount",
    "CampaignsListResponse",
    "CampaignCreationRequest",
    "CampaignCreationResponse",
    "CampaignDetailResponse",
    "LoginRequest",
    "AuthResponse",
    "LogoutRequest",
    "LogoutResponse",
    "TokenValidationResponse",
    "RefreshTokenRequest",
    "CSRFTokenResponse",
    "InvalidationRequest",
    "ChunkInRequest",
    "GuestSessionResponse",
    "WorkspaceCharacterCreateRequest",
    "WorkspaceCharacterUpdateRequest",
]
