apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-testing-config
  namespace: ai-testing
  labels:
    app.kubernetes.io/name: novel-engine-ai-testing
    app.kubernetes.io/component: configuration
data:
  # Application configuration
  app.yml: |
    ai_testing:
      orchestration:
        services_base_port: 8000
        health_check_interval_seconds: 30
        health_cache_ttl_seconds: 60
        
      browser_automation:
        default_timeout_seconds: 30
        default_viewport_width: 1920
        default_viewport_height: 1080
        headless: true
        enable_video_recording: true
        video_quality: "high"
        screenshot_on_failure: true
        
      api_testing:
        default_timeout_seconds: 30
        max_retries: 3
        retry_delay_seconds: 1
        default_max_response_time_ms: 2000
        
      ai_quality:
        llm_judge:
          default_models:
            - "gpt-4"
            - "gemini-pro"
          timeout_seconds: 60
          max_retries: 2
          
      results_aggregation:
        storage_backend: "filesystem"
        retention_days: 30
        report_formats:
          - "json"
          - "html"
          - "pdf"
          
      notification:
        channels:
          email:
            smtp_timeout_seconds: 30
          slack:
            timeout_seconds: 10
          webhook:
            timeout_seconds: 15
        rate_limits:
          email: 10  # per hour
          slack: 60   # per hour
          webhook: 100 # per hour

  # Logging configuration
  logging.yml: |
    version: 1
    disable_existing_loggers: false
    formatters:
      default:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      detailed:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: default
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: detailed
        filename: /app/logs/ai_testing.log
        maxBytes: 10485760  # 10MB
        backupCount: 5
    loggers:
      ai_testing:
        level: DEBUG
        handlers: [console, file]
        propagate: false
      uvicorn:
        level: INFO
        handlers: [console]
        propagate: false
    root:
      level: INFO
      handlers: [console]

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-testing-secrets
  namespace: ai-testing
  labels:
    app.kubernetes.io/name: novel-engine-ai-testing
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # API Keys (to be filled with actual values)
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  GOOGLE_API_KEY: ""
  
  # SMTP Configuration
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  
  # Slack Configuration
  SLACK_WEBHOOK_URL: ""
  
  # Database URLs (if needed)
  DATABASE_URL: ""
  REDIS_URL: "redis://ai-testing-redis:6379"