apiVersion: v1
kind: Namespace
metadata:
  name: ai-testing
  labels:
    name: ai-testing
    app.kubernetes.io/name: novel-engine-ai-testing
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-testing-limits
  namespace: ai-testing
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-testing-quota
  namespace: ai-testing
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"