import type { Project, StudioDocument } from '@/app/types/studio';

export interface WholeBookChapter {
  readonly id: string;
  readonly title: string;
}

/**
 * #318 needs-generation rule: a chapter needs a whole-book draft iff its
 * current revision was not produced by an accepted AI proposal. The server's
 * closed revision-source vocabulary is `author | ai-accepted | restore`
 * (`server/src/contexts/studio/domain/kinds.ts`), so seeded, hand-written,
 * imported, and restored chapters are all regenerated by the loop. Revisions
 * are immutable, so every replaced current state stays restorable from
 * document history.
 */
export function needsGeneration(document: StudioDocument): boolean {
  return document.revision_source !== 'ai-accepted';
}

/**
 * Reading order per ADR-0005: volume position first, then in-volume chapter
 * position. Chapters without a resolved volume link fall back to the first
 * volume exactly like the navigator's grouping, even though ADR-0005
 * guarantees every chapter is placed.
 */
export function readingOrderChapters(project: Project): StudioDocument[] {
  const chapters = (project.documents ?? []).filter((document) => document.kind === 'chapter');
  const volumes = [...(project.volumes ?? [])].sort(
    (left, right) => left.position - right.position,
  );
  const volumeRank = new Map(volumes.map((volume, index) => [volume.id, index]));
  const fallbackRank = volumes.length > 0 ? (volumeRank.get(volumes[0].id) ?? 0) : 0;
  const rankOf = (document: StudioDocument): number =>
    document.volume_id ? (volumeRank.get(document.volume_id) ?? fallbackRank) : fallbackRank;
  // filter() above already produced a fresh array, so sorting it never
  // mutates the project payload's own list.
  return chapters.sort((left, right) => {
    const leftRank = rankOf(left);
    const rightRank = rankOf(right);
    return leftRank !== rightRank ? leftRank - rightRank : left.position - right.position;
  });
}

/**
 * The ordered set of chapters the whole-book loop will draft and accept.
 * Recomputed at every start, which is what makes resume work: starting again
 * always begins at the first chapter without an accepted AI revision (#318).
 */
export function wholeBookPlan(project: Project): WholeBookChapter[] {
  const plan: WholeBookChapter[] = [];
  for (const document of readingOrderChapters(project)) {
    if (!needsGeneration(document)) continue;
    plan.push({ id: document.id, title: document.title });
  }
  return plan;
}
