"""
Scene Entity

Represents a scene within a chapter. Scenes contain narrative content
and present choices to the user.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from src.contexts.narrative.domain.entities.choice import Choice
from src.contexts.narrative.domain.types import SceneId, SceneType
from src.shared.domain.base.entity import Entity


@dataclass(kw_only=True, eq=False)
class Scene(Entity[SceneId]):
    """
    A scene in the narrative.

    AI注意:
    - Scenes are the core narrative units
    - Each scene presents content and optionally choices
    - Scene order matters for narrative flow
    - Content can be generated by AI or written by humans
    """

    chapter_id: str = field(default="")
    scene_number: int = field(default=0)
    title: Optional[str] = None
    content: str = field(default="")
    scene_type: SceneType = field(default="narrative")
    choices: List[Choice] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def validate(self) -> None:
        """Validate scene invariants.

        Required by Entity base class.
        """
        if not self.chapter_id:
            raise ValueError("Scene must belong to a chapter")

        if self.scene_number < 1:
            raise ValueError("Scene number must be positive")

        if len(self.content) > 50000:
            raise ValueError("Scene content cannot exceed 50000 characters")

        # Validate scene type
        valid_types = {
            "opening",
            "narrative",
            "dialogue",
            "action",
            "decision",
            "climax",
            "ending",
        }
        if self.scene_type not in valid_types:
            raise ValueError(f"Invalid scene type: {self.scene_type}")

    @property
    def is_decision_point(self) -> bool:
        """Check if this scene presents choices to the user."""
        return len(self.choices) > 0

    @property
    def has_multiple_paths(self) -> bool:
        """Check if this scene leads to multiple narrative branches."""
        available_choices = [c for c in self.choices if c.next_scene_id]
        return len(available_choices) > 1

    def add_choice(self, choice: Choice) -> None:
        """
        Add a choice to this scene.

        Args:
            choice: The choice to add

        Raises:
            ValueError: If maximum choices reached
        """
        if len(self.choices) >= 5:
            raise ValueError("Scene cannot have more than 5 choices")

        self.choices.append(choice)
        self.updated_at = datetime.utcnow()

    def remove_choice(self, choice_id: str) -> None:
        """Remove a choice from this scene."""
        self.choices = [c for c in self.choices if str(c.id) != choice_id]
        self.updated_at = datetime.utcnow()

    def get_available_choices(self, context: Dict[str, Any]) -> List[Choice]:
        """
        Get choices available given the current narrative context.

        Args:
            context: Current narrative context

        Returns:
            List of choices that can be presented to the user
        """
        return [c for c in self.choices if c.is_available(context)]

    def select_choice(
        self, choice_id: str, context: Dict[str, Any]
    ) -> tuple[Choice, Dict[str, Any], Optional[str]]:
        """
        Select a choice and apply its consequences.

        Args:
            choice_id: ID of the selected choice
            context: Current narrative context

        Returns:
            Tuple of (selected_choice, updated_context, next_scene_id)

        Raises:
            ValueError: If choice not found or not available
        """
        choice = next((c for c in self.choices if str(c.id) == choice_id), None)

        if not choice:
            raise ValueError(f"Choice {choice_id} not found in scene")

        if not choice.is_available(context):
            raise ValueError(f"Choice {choice_id} is not available in current context")

        # Apply consequences
        updated_context = choice.apply_consequences(context)

        return choice, updated_context, choice.next_scene_id

    def update_content(self, new_content: str) -> None:
        """Update scene content."""
        if len(new_content) > 50000:
            raise ValueError("Content too long")

        self.content = new_content
        self.updated_at = datetime.utcnow()

    def to_dict(self) -> Dict[str, Any]:
        """Convert scene to dictionary for serialization."""
        return {
            "id": str(self.id),
            "chapter_id": self.chapter_id,
            "scene_number": self.scene_number,
            "title": self.title,
            "content": self.content,
            "scene_type": self.scene_type,
            "choices": [c.to_dict() for c in self.choices],
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
        }
