apiVersion: v1
kind: ServiceAccount
metadata:
  name: novel-engine
  labels:
    app: novel-engine
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: novel-engine
  labels:
    app: novel-engine
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: novel-engine
  labels:
    app: novel-engine
subjects:
- kind: ServiceAccount
  name: novel-engine
  namespace: default
roleRef:
  kind: Role
  name: novel-engine
  apiGroup: rbac.authorization.k8s.io