global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'novel-engine'
    environment: 'development'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Novel Engine Application Services
  - job_name: 'novel-engine-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  - job_name: 'novel-engine-story-engine'
    static_configs:
      - targets: ['host.docker.internal:8001']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  - job_name: 'novel-engine-character-service'
    static_configs:
      - targets: ['host.docker.internal:8002']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  - job_name: 'novel-engine-campaign-manager'
    static_configs:
      - targets: ['host.docker.internal:8003']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  - job_name: 'novel-engine-memory-service'
    static_configs:
      - targets: ['host.docker.internal:8004']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Infrastructure Services
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['host.docker.internal:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['host.docker.internal:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['host.docker.internal:9308']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter (if deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker container metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 30s
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB