name: Simple Local Test

on:
  workflow_dispatch:
  push:

jobs:
  simple-backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test environment
      run: |
        echo "🐍 Python version:"
        python3 --version
        echo "📦 Pip version:"
        pip3 --version
        echo "📁 Current directory:"
        pwd
        echo "📋 Directory contents:"
        ls -la

    - name: Test Python basic functionality
      run: |
        python3 -c "print('✅ Python is working!')"
        python3 -c "import sys; print(f'Python path: {sys.executable}')"
        python3 -c "import os; print(f'Working directory: {os.getcwd()}')"

    - name: Install basic dependencies
      run: |
        pip3 install --user pytest requests pyyaml
        echo "✅ Basic dependencies installed"

    - name: Test basic Python imports
      run: |
        python3 -c "
        try:
            import pytest
            import requests
            import yaml
            import sqlite3
            print('✅ All required modules available')
        except ImportError as e:
            print(f'❌ Import error: {e}')
            exit(1)
        "

  simple-system-info:
    runs-on: ubuntu-latest
    
    steps:
    - name: System information
      run: |
        echo "🖥️ System Info:"
        echo "OS: $(uname -a)"
        echo "Architecture: $(uname -m)"
        echo "CPU cores: $(nproc)"
        echo "Memory: $(free -h)"
        echo "Disk space: $(df -h /)"
        
    - name: Docker information
      run: |
        echo "🐳 Docker Info:"
        docker --version || echo "Docker not available"
        docker info || echo "Docker daemon not running"