name: Test Validation - Act CLI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-tests:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python 3.12
      if: ${{ !env.ACT }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: requirements.txt
        
    - name: Set up Python for act
      if: ${{ env.ACT }}
      shell: bash
      run: |
        echo "Current Python: $(python3 --version 2>&1)"
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -qq
        apt-get install -y -qq software-properties-common
        add-apt-repository -y ppa:deadsnakes/ppa
        apt-get update -qq
        apt-get install -y -qq python3.12 python3.12-distutils python3-pip
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1
        python3 --version
        curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12
        python3 -m pip --version
        
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        pip install pytest pytest-asyncio pytest-cov pytest-mock
        echo "✅ Dependencies installed"
        
    - name: Run Phase 2 exception tests
      shell: bash
      run: |
        echo "🧪 Running Phase 2 custom exception tests..."
        python -m pytest tests/unit/core/test_exceptions.py -v --tb=short
        echo "✅ Phase 2 exception tests completed"
        
    - name: Run Iron Laws integration tests
      shell: bash
      run: |
        echo "🧪 Running Iron Laws integration tests..."
        python -m pytest tests/unit/core/test_iron_laws_processor.py::TestIronLawsIntegration -v --tb=short
        echo "✅ Iron Laws integration tests completed"
        
    - name: Run full unit test suite
      shell: bash
      run: |
        echo "🧪 Running full unit test suite..."
        python -m pytest tests/unit/ -v --tb=no -q
        echo "✅ Full test suite completed"
        
    - name: Test summary
      if: always()
      shell: bash
      run: |
        echo "📊 Test Validation Summary"
        echo "=========================="
        echo "Phase 2 Tests: Check output above"
        echo "Iron Laws Tests: Check output above"
        echo "Full Suite: Check output above"
